[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "notebook>=7.4.3",
    "numpy>=2.2.6",
    "torch==2.7.0",
]
